const northernArt = [
  {
    id: 1,
    title: "Albert Hall Memorial",
    image: "northern-images/albert-memorial.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "6 x 8 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/top-of-the-hill/",
  },
  {
    id: 2,
    title: "Big Dwelling",
    image: "northern-images/big-dwelling.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "6 x 8 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/big-dwelling/",
  },
  {
    id: 3,
    title: "Blue House",
    image: "northern-images/blue-house.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "6 x 8 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/blue-house/",
  },
  {
    id: 4,
    title: "Castlefield Basin",
    image: "northern-images/castlefield-basin.jpeg",
    medium: "acrylic on board",
    price: "£565",
    size: "10 x 12 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/castlefield-basin/",
  },
  {
    id: 5,
    title: "Evening Kick-off",
    image: "northern-images/evening-kick-off.jpeg",
    medium: "acrylic on board",
    price: "£565",
    size: "10 x 12 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/evening-kick-off/",
  },
  {
    id: 6,
    title: "Girder Bridge, Castlefield",
    image: "northern-images/girder-bridge-castlefield.jpeg",
    medium: "acrylic on board",
    price: "£565",
    size: "10 x 12 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/girder-bridge-castlefield/",
  },
  {
    id: 7,
    title: "House with Three Storeys",
    image: "northern-images/house-with-three-storys.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "6 x 8 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/house-with-three-storeys/",
  },
  {
    id: 8,
    title: "Long House",
    image: "northern-images/long-house.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "6 x 8 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/long-house/",
  },
  {
    id: 9,
    title: "Looking South to Blackfriars Bridge",
    image: "northern-images/looking-south-to-blackfriars-bridge.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "6 x 8 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/looking-south-to-blackfriars-bridge/",
  },
  {
    id: 10,
    title: "Manchester Mix",
    image: "northern-images/manchester-mix.jpeg",
    medium: "acrylic on board",
    price: "£995",
    size: "23 x 23 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/manchester-mix/",
  },
  {
    id: 11,
    title: "Manchester Rising II",
    image: "northern-images/manchester-rising-2.jpeg",
    medium: "acrylic on board",
    price: "£575",
    size: "9 x 24 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/manchester-rising-ii/",
  },
  {
    id: 12,
    title: "Manchester Skyline",
    image: "northern-images/manchester-skyline.jpeg",
    medium: "acrylic on board",
    price: "£575",
    size: "7 x 24 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/manchester-skyline/",
  },
  {
    id: 13,
    title: "Neighbours",
    image: "northern-images/neighbours.jpeg",
    medium: "acrylic on board",
    price: "£345",
    size: "8 x 10 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/neighbours/",
  },
  {
    id: 14,
    title: "New Downtown Manchester",
    image: "northern-images/new-downtown-manchester.jpeg",
    medium: "acrylic on board",
    price: "£345",
    size: "6 x 16 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/new-downtown-manchester/",
  },
  {
    id: 15,
    title: "Old & New",
    image: "northern-images/old-and-new.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "6 x 8 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/old-and-new-2/",
  },
  {
    id: 16,
    title: "One Nil",
    image: "northern-images/one-nil.jpeg",
    medium: "acrylic on board",
    price: "£725",
    size: "10 x 21 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/one-nil/",
  },
  {
    id: 17,
    title: "Out all Night",
    image: "northern-images/out-all-night.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "6 x 8 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/out-all-night/",
  },
  {
    id: 18,
    title: "Red House",
    image: "northern-images/red-house.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "6 x 8 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/red-house/",
  },
  {
    id: 19,
    title: "Remaking Manchester",
    image: "northern-images/remaking manchester.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "9 x 24 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/remaking-manchester/",
  },
  {
    id: 20,
    title: "Salford Evening Light, Tug-boat",
    image: "northern-images/salford-evening-light-tug-boat.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "9 x 24 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/salford-evening-light-tug-boat/",
  },
  {
    id: 21,
    title: "Stockport Plaza",
    image: "northern-images/stockport-plaza.jpeg",
    medium: "acrylic on board",
    price: "£445",
    size: "10 x 12 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/stockport-plaza/",
  },
  {
    id: 22,
    title: "Street Scene",
    image: "northern-images/street-scene.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "7 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/street-scene/",
  },
  {
    id: 23,
    title: "The Crossroads",
    image: "northern-images/the-crossroads.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "6 x 8 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/the-crossroads/",
  },
  {
    id: 24,
    title: "The Little Terror",
    image: "northern-images/the-little-terror.jpeg",
    medium: "acrylic on board",
    price: "£445",
    size: "10 x 12 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/the-little-terror/",
  },
  {
    id: 25,
    title: "The Tower",
    image: "northern-images/the-tower.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "6 x 8 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/the-tower/",
  },
  {
    id: 26,
    title: "Top of The Hill",
    image: "northern-images/top-of-the-hill.jpeg",
    medium: "acrylic on board",
    price: "£325",
    size: "6 x 8 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/top-of-the-hill/",
  },
  {
    id: 27,
    title: "Town Hall",
    image: "northern-images/town-hall.jpeg",
    medium: "acrylic on board",
    price: "£445",
    size: "10 x 12 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/town-hall/",
  },
  {
    id: 28,
    title: "Training Day",
    image: "northern-images/training-day.jpeg",
    medium: "acrylic on board",
    price: "£625",
    size: "10 x 16 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/training-day/",
  },
  {
    id: 29,
    title: "Winter Games",
    image: "northern-images/winter-games.jpeg",
    medium: "acrylic on board",
    price: "£445",
    size: "10 x 12 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/winter-games/",
  },
  {
    id: 30,
    title: "Yellow House",
    image: "northern-images/yellow-house.jpeg",
    medium: "acrylic on board",
    price: "£445",
    size: "9 x 11 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman/yellow-house/",
  },
];

const northernArtOutput = northernArt.map(function (image) {
  return (document.getElementById("northern-gallery-output").innerHTML += `
  
      <div class="image-box">
          <h2>${image.title}</h2>
          <img class="img-adjust" src="${image.image}">
          <p class="text-top">Medium: ${image.medium}</p>
          <p>Price: ${image.price}</p>
          <p>Size: ${image.size}</p>
          <p>Where to buy: <a href="${image.link}">County Art</a></p>
      </div>
  
      `);
});

export { northernArt, northernArtOutput };
