const sheepArt = [
  {
    id: 1,
    title: "After the Shower",
    image: "sheep-images/after-the-shower.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/after-the-shower/",
  },
  {
    id: 2,
    title: "All is Quiet",
    image: "sheep-images/all-is-quiet.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/all-is-quiet/",
  },
  {
    id: 3,
    title: "Apple Tree and Sheep",
    image: "sheep-images/apple-tree-and-sheep.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/apple-tree-and-sheep/",
  },
  {
    id: 4,
    title: "Beau Soleil",
    image: "sheep-images/beau-soleit.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/beau-soleil/",
  },
  {
    id: 5,
    title: "Before the Snow",
    image: "sheep-images/before-the-snow.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/before-the-snow/",
  },
  {
    id: 6,
    title: "Bringing them all back Home",
    image: "sheep-images/bringing-them-all-back-home.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/bringing-them-all-back-home/",
  },
  {
    id: 7,
    title: "By the Lake",
    image: "sheep-images/by-the-lake.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/by-the-lake/",
  },
  {
    id: 8,
    title: "Cat with the Red collar",
    image: "sheep-images/cat-with-the-red-collar.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/cat-with-the-red-collar/",
  },
  {
    id: 9,
    title: "Checking up",
    image: "sheep-images/checking-up.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/checking-up/",
  },
  {
    id: 10,
    title: "Evening Gathering",
    image: "sheep-images/evening-gathering.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/evening-gathering/",
  },
  {
    id: 11,
    title: "Evening Training",
    image: "sheep-images/evening-train.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/evening-train/",
  },
  {
    id: 12,
    title: "Full Moon",
    image: "sheep-images/full-moon.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/full-moon/",
  },
  {
    id: 13,
    title: "Golden Moon",
    image: "sheep-images/golden-moon.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/golden-moon/",
  },
  {
    id: 14,
    title: "Half way House",
    image: "sheep-images/halfway-house.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/half-way-house/",
  },
  {
    id: 15,
    title: "Hard Life",
    image: "sheep-images/hard-life.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/hard-life/",
  },
  {
    id: 16,
    title: "Hill Sheep",
    image: "sheep-images/hill-sheep.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/hill-sheep/",
  },
  {
    id: 17,
    title: "In the Cornfield",
    image: "sheep-images/in-the-cornfield.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/in-the-cornfield/",
  },
  {
    id: 18,
    title: "In the Shade",
    image: "sheep-images/in-the-shade.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/in-the-shade/",
  },
  {
    id: 19,
    title: "Last of the Day",
    image: "sheep-images/last-of-the-day.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/last-of-the-day-1/",
  },
  {
    id: 20,
    title: "Limestone Sheep",
    image: "sheep-images/limestone-sheep.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/limestone-sheep/",
  },
  {
    id: 21,
    title: "Midnight, still air",
    image: "sheep-images/midnight-still-air.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/midnight-still-air/",
  },
  {
    id: 22,
    title: "Misty Vista",
    image: "sheep-images/misty-vista.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/misty-vista/",
  },
  {
    id: 23,
    title: "Moon Meadow",
    image: "sheep-images/moon-meadow.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/moon-meadow/",
  },
  {
    id: 24,
    title: "Moonscape",
    image: "sheep-images/moonscape.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/moonscape/",
  },
  {
    id: 25,
    title: "On A Mission",
    image: "sheep-images/on-a-mission.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/on-a-mission/",
  },
  {
    id: 26,
    title: "Open Space",
    image: "sheep-images/open-space.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/open-space/",
  },
  {
    id: 27,
    title: "Out Numbered",
    image: "sheep-images/out-numbered.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/out-numbered/",
  },
  {
    id: 28,
    title: "Pennine Posers",
    image: "sheep-images/pennine-posers.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/pennine-posers/",
  },
  {
    id: 29,
    title: "Purple Light",
    image: "sheep-images/purple-light.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/purple-light/",
  },
  {
    id: 30,
    title: "Sheep Rusticana",
    image: "sheep-images/sheep-rusticana.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/sheep-rusticana/",
  },
  {
    id: 31,
    title: "Summer Evening with Sheep",
    image: "sheep-images/summer-evening-with-sheep.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/summer-evening-with-sheep/",
  },
  {
    id: 32,
    title: "Sun on the Moor",
    image: "sheep-images/sun-on-the-moor.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/sun-on-the-moor/",
  },
  {
    id: 33,
    title: "The Farm Cat",
    image: "sheep-images/the-farm-cat.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/the-farm-cat/",
  },
  {
    id: 34,
    title: "The Sentinal",
    image: "sheep-images/the-sentinal.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/the-sentinal/",
  },
  {
    id: 35,
    title: "The Trespassers",
    image: "sheep-images/the-trespassers.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/the-trespassers/",
  },
  {
    id: 36,
    title: "They Never Stray too far",
    image: "sheep-images/they-never-stray-too-far.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/they-never-stray-too-far/",
  },
  {
    id: 37,
    title: "Trials of a Sheep Dog",
    image: "sheep-images/trails-of-a-sheep-dog.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/trials-of-a-sheep-dog/",
  },
  {
    id: 38,
    title: "Trying to Help...",
    image: "sheep-images/trying-to-help.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/trying-to-help/",
  },
  {
    id: 39,
    title: "What's New?",
    image: "sheep-images/whats-new.jpeg",
    medium: "acrylic on board",
    price: "£295",
    size: "9 x 9 inches",
    link: "http://www.countygalleries.co.uk/artists/david-alderman-sheep-paintings/whats-new/",
  },
];

const sheepArtOutput = sheepArt.map(function (image) {
  return (document.getElementById("sheep-gallery-output").innerHTML += `
        
        <div class="image-box">
        <h2>${image.title}</h2>
        <img class="img-adjust" src="${image.image}">
        <p class="text-top">Medium: ${image.medium}</p>
        <p>Price: ${image.price}</p>
        <p>Size: ${image.size}</p>
        <p>Where to buy: <a href="${image.link}">County Art</a></p>
        </div>
        
        `);
});
export { sheepArt, sheepArtOutput };
